---
- name: Install prerequisites
  ansible.builtin.include_tasks: prereq.yml

- name: Configure acme pve certificate
  ansible.builtin.include_tasks: pve-acme.yml

- name: Ensure certificates are ordered
  ansible.builtin.meta: flush_handlers
